chartConfig:
  type: table
description: Failed task runs by integration and job.
metricQuery:
  dimensions:
    - fct_task_runs_integration
    - fct_task_runs_integration_job
  exploreName: fct_task_runs
  filters:
    dimensions:
      and: []
  limit: 20
  metrics:
    - fct_task_runs_failed_task_runs
  sorts:
    - fieldId: fct_task_runs_failed_task_runs
      descending: true
  tableCalculations: []
name: Ops Breakdown Failures by Integration
slug: ops-breakdown-failures-by-integration
spaceSlug: operations
tableName: fct_task_runs
version: 1
