chartConfig:
  type: table
description: Failed task runs by integration and job.
metricQuery:
  dimensions:
    - dim_integrations_integration
    - dim_integrations_integration_job
  exploreName: dim_integrations
  filters:
    dimensions:
      and: []
  limit: 20
  metrics:
    - dim_integrations_integration_failed_task_runs
  sorts:
    - fieldId: dim_integrations_integration_failed_task_runs
      descending: true
  tableCalculations: []
name: Ops Breakdown Failures by Integration
slug: ops-breakdown-failures-by-integration
spaceSlug: operations
tableName: dim_integrations
version: 1
