chartConfig:
  config:
    selectedField: dim_pipelines_total_pipeline_runs
    showBigNumberLabel: true
  type: big_number
description: Total pipeline runs for the selected date range.
metricQuery:
  dimensions: []
  exploreName: dim_pipelines
  metrics:
    - dim_pipelines_total_pipeline_runs
  filters:
    dimensions:
      and: []
  limit: 500
  sorts: []
  tableCalculations: []
name: Ops KPI Pipeline Runs
slug: ops-kpi-pipeline-runs
spaceSlug: operations
tableName: dim_pipelines
version: 1
