chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: metrics_daily_summary_summary_date_day
            yRef:
              field: metrics_daily_summary_daily_pipeline_runs
          isFilteredOut: false
          type: line
    layout:
      xField: metrics_daily_summary_summary_date_day
      yField:
        - metrics_daily_summary_daily_pipeline_runs
  type: cartesian
description: Daily pipeline run volume.
metricQuery:
  dimensions:
    - metrics_daily_summary_summary_date_day
  exploreName: metrics_daily_summary
  filters:
    dimensions:
      and: []
  limit: 500
  metrics:
    - metrics_daily_summary_daily_pipeline_runs
  sorts:
    - fieldId: metrics_daily_summary_summary_date_day
      descending: false
  tableCalculations: []
name: Ops Trend Daily Pipeline Runs
slug: ops-trend-daily-runs
spaceSlug: operations
tableName: metrics_daily_summary
version: 1
