name: Ops Breakdown Failures by Integration
description: Failed task runs by integration and job.
tableName: dim_integrations
metricQuery:
  exploreName: dim_integrations
  dimensions:
    - dim_integrations_integration
    - dim_integrations_integration_job
  metrics:
    - dim_integrations_integration_failed_task_runs
  filters:
    dimensions: []
  sorts:
    - fieldId: dim_integrations_integration_failed_task_runs
      descending: true
  limit: 20
chartConfig:
  type: table
slug: ops-breakdown-failures-by-integration
spaceSlug: operations
version: 1
