chartConfig:
  type: big_number
description: Total pipeline runs for the selected date range.
metricQuery:
  dimensions: []
  exploreName: fct_pipeline_runs
  metrics:
    - fct_pipeline_runs_pipeline_runs_count
  filters:
    dimensions:
      and: []
  limit: 500
  sorts: []
  tableCalculations: []
name: Ops KPI Pipeline Runs
slug: ops-kpi-pipeline-runs
spaceSlug: operations
tableName: fct_pipeline_runs
version: 1
