chartConfig:
  type: big_number
description: Total failed task runs for the selected period.
metricQuery:
  dimensions: []
  exploreName: fct_task_runs
  filters:
    dimensions:
      and: []
  limit: 500
  metrics:
    - fct_task_runs_failed_task_runs
  sorts: []
  tableCalculations: []
name: Ops KPI Task Failure Rate
slug: ops-kpi-task-failure-rate
spaceSlug: operations
tableName: fct_task_runs
version: 1
