chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: fct_daily_metrics_summary_date_day
            yRef:
              field: fct_daily_metrics_daily_pipeline_runs
          isFilteredOut: false
          type: line
    layout:
      xField: fct_daily_metrics_summary_date_day
      yField:
        - fct_daily_metrics_daily_pipeline_runs
  type: cartesian
description: Daily pipeline run volume.
metricQuery:
  dimensions:
    - fct_daily_metrics_summary_date_day
  exploreName: fct_daily_metrics
  filters:
    dimensions:
      and: []
  limit: 500
  metrics:
    - fct_daily_metrics_daily_pipeline_runs
  sorts:
    - fieldId: fct_daily_metrics_summary_date_day
      descending: false
  tableCalculations: []
name: Ops Trend Daily Pipeline Runs
slug: ops-trend-daily-runs
spaceSlug: operations
tableName: fct_daily_metrics
version: 1
