chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: fct_pipeline_runs_created_date_day
            yRef:
              field: fct_pipeline_runs_failed_runs
          isFilteredOut: false
          type: line
        - encode:
            xRef:
              field: fct_pipeline_runs_created_date_day
            yRef:
              field: fct_pipeline_runs_warning_runs
          isFilteredOut: false
          type: line
    layout:
      xField: fct_pipeline_runs_created_date_day
      yField:
        - fct_pipeline_runs_failed_runs
        - fct_pipeline_runs_warning_runs
  type: cartesian
description: Daily pipeline, task, and operation failure rates.
metricQuery:
  dimensions:
    - fct_pipeline_runs_created_date_day
  exploreName: fct_pipeline_runs
  filters:
    dimensions:
      and: []
  limit: 500
  metrics:
    - fct_pipeline_runs_failed_runs
    - fct_pipeline_runs_warning_runs
  sorts:
    - fieldId: fct_pipeline_runs_created_date_day
      descending: false
  tableCalculations: []
name: Ops Trend Daily Failure Rates
slug: ops-trend-failure-rate
spaceSlug: operations
tableName: fct_pipeline_runs
version: 1
