name: dbt CI

on:
  pull_request:
    branches:
      - main

env:
  GCP_REPO: ${{ secrets.BIGQUERY_REPO }}
  PRIVATE_KEY_ID: ${{ secrets.BIGQUERY_PRIVATE_KEY_ID }}
  PRIVATE_KEY: ${{ secrets.BIGQUERY_PRIVATE_KEY }}
  CLIENT_EMAIL: ${{ secrets.BIGQUERY_CLIENT_EMAIL }}
  CLIENT_ID: ${{ secrets.BIGQUERY_CLIENT_ID }}
  CLIENT_CERT_URL: ${{ secrets.BIGQUERY_CLIENT_CERT_URL }}

jobs:
  warehouse_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        warehouse: ["bigquery"]

  sqlfluff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: main

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run SQLFluff lint
        run: |
          poetry run sqlfluff lint models/ --dialect ${{ matrix.warehouse }} --processes 4

#  dbt-core-slimci-action:
#    needs: sql-lint
#    runs-on: ubuntu-latest
#    environment: production
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run dbt Task in Pipeline
#        uses: orchestra-hq/run-pipeline@v1
#        with:
#          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
#          pipeline_id: ${{ secrets.ORCHESTRA_PIPELINE_ID_CI }}
#          poll_interval: 20
#          environment: CI
#          task_ids: run_dbt
#          run_inputs: |
#            {
#              "dbt_command": " build -s state:modified+ --defer --state latest_production --exclude tag:metadata",
#              "dbt_branch": "${{ github.head_ref }}"
#            }
