name: dbt CI

on:
  pull_request:
    branches:
      - main

env:
  GCP_REPO: ${{ secrets.BIGQUERY_REPO }}
  PRIVATE_KEY_ID: ${{ secrets.BIGQUERY_PRIVATE_KEY_ID }}
  PRIVATE_KEY: ${{ secrets.BIGQUERY_PRIVATE_KEY }}
  CLIENT_EMAIL: ${{ secrets.BIGQUERY_CLIENT_EMAIL }}
  CLIENT_ID: ${{ secrets.BIGQUERY_CLIENT_ID }}
  CLIENT_CERT_URL: ${{ secrets.BIGQUERY_CLIENT_CERT_URL }}

jobs:
  sqlfluff-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        warehouse: ["bigquery"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SQLFluff Task in Pipeline
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: ${{ secrets.ORCHESTRA_METADATA_PIPELINE_ID }}
          poll_interval: 20
          environment: Staging
          task_ids: aa8783d2-5c3f-4cf1-a6c9-bef31ee71f9b
          run_inputs: |
            {
              "git_branch": "${{ github.head_ref }}",
              "warehouse": "${{ matrix.warehouse }}"
            }

  dbt-core-slimci-action:
    needs: sqlfluff-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run dbt Task in Pipeline
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: ${{ secrets.ORCHESTRA_METADATA_PIPELINE_ID }}
          poll_interval: 20
          environment: CI
          task_ids: 9e7c692c-b686-4fe2-a406-e7123fa1ef1c
          run_inputs: |
            {
              "dbt_command": " compile",
              "dbt_branch": "${{ github.head_ref }}"
            }
